### PR TITLE
update to zeek 4.2.1

### PR DESCRIPTION
**Pull request by alextibbles**

### CODE REVIEW

**Comment by timwoj** [comment]
With the 5.0 series of releases out, is this still desired?

**Comment by JustinAzoff** [comment]
I think with the work we did to add auto building of container images from the main repository, this might not be needed at all anymore... just as long as we ensure that everything is tagged properly moving forward.

**Comment by alextibbles** [comment]
Thanks! I had got 5.x working as well, which also seems to be redundant now. I look forward to using the pre-built images!

**Comment by JustinAzoff** [comment]
Yeah, the new pre-built ones should be ready to go:

```
$ docker run -t -i --rm zeek/zeek:5.2.0 zeek --version
Unable to find image 'zeek/zeek:5.2.0' locally
5.2.0: Pulling from zeek/zeek
3f9582a2cbe7: Pull complete 
2d1d6eef6f90: Pull complete 
4df3fa938ca5: Pull complete 
0dec0ab32c0b: Pull complete 
Digest: sha256:d7d9debd155daabfda7f79c360a35fc0d4fbc284104d7a49994c718a5e316258
Status: Downloaded newer image for zeek/zeek:5.2.0
zeek version 5.2.0
```

**Pull request closed without merging**
