### PR TITLE
Refactor to use a single Dockerfile for Zeek 3.0.0+

### PR DESCRIPTION
**Pull request by kahou82**
This patchset is to refactor the current docker build structure such that
for Zeek 3.0.0+ we will use a single Dockerfile by passing more build-arg arguments.

Also, this patchset fixes a missing file issue in 2.6.x.

### CODE REVIEW

**Comment by JustinAzoff** [comment]
I wonder if we should also just replace that Makefile with a shell script or python script.. all that variable expansion stuff is confusing, and a simple

      ./build.py 3.1.0

might be a lot simpler

**Comment by kahou82** [comment]
@JustinAzoff , thanks for your feedback. 

Regarding if we use shell/python, it depends if there is any other pipeline depends on this docker build process. If we can consolidate to one single Dockerfile, we can skip those variable expansions but just using:

`make build VER=3.1.0`

The current problem is that there are some Dockerfiles supported for older versions and they vary a lot.

Using python is ok but we have to consider other build pipelines dependency (e.g. they have to install extra python packages in the future.) 

Anyway, I am new to this community. Let me know how you want to do it and I am happy to help.

Btw, can you share the CI test script? It is failing and looks that my change doesn't consider that test case.

**Comment by JustinAzoff** [comment]
I don't actually know why CI is running.. might be related to the Cirrus setup on the main zeek repo.. I didn't set it up here.

Good point with the python stuff.. I bet with a little more work we'll be able to get it down to one Dockerfile.

**Comment by kahou82** [comment]
Sure, do you want to get this one merge first and we can fix the old Dockerfile in the next pull request?

**Comment by kahou82** [comment]
re CI issue, is it possible to see what is running in Zeek main repo?

**Comment by JustinAzoff** [comment]
https://github.com/zeek/zeek/blob/master/.cirrus.yml is the config for the main repo.. but i think for here it might just be trying to do some auto test thing, since there's no .cirrus config but it finds the Dockerfile.
We could probably get that to pass by at least specifying a default version, which might not be a bad idea in general

**Pull request merged**
